In [2]:
import numpy as np

In [3]:
poop = np.full((1003, 12), 1, dtype=int)

poop[0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
magnitudes = poop.sum(axis=1, keepdims=1)
vals = (poop/magnitudes)

vals[0]

array([0.08333333, 0.08333333, 0.08333333, 0.08333333, 0.08333333,
       0.08333333, 0.08333333, 0.08333333, 0.08333333, 0.08333333,
       0.08333333, 0.08333333])

In [9]:
magnitudes[0]

array([12])

In [10]:
shuffle = 101 / 4

In [26]:
numNoteShuffles = 1
shuffle_points = [int(i * 105 / numNoteShuffles) for i in range(1, numNoteShuffles)]  # Calculate exact shuffle points


In [27]:
shuffle_points

[]

In [28]:
100 in shuffle_points

False